---
# file: site.yml
# intended to be run like: ansible-playbook -i inventory site.yml
- name: Set up servers
  hosts: all
  remote_user: control

  roles:
    - servers
    - buildagents
    - testers